spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/location?characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20

  mail:
    host: smtp.163.com
    username: location_2019@163.com
    password: location2019
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 5MB #tomcat参数

server:
  port: 8090

logging:
  level:
    root: INFO
    com.scut.indoorLocation.dao: WARN
  file:
    path: "/root/Downloads/back_end/log"

levelDB:
  dir:
    path: "/root/Downloads/back_end/levelDB"


#mqtt服务器配置
mqtt:
  host: "39.99.131.85"
  port: 1883


#图片地址
image:
  dir:
    path: "/var/www/images"