#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/location?characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.163.com
    username: location_2019@163.com
    password: location2019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      default-encoding:
        UTF-8


#tomcat参数
server:
  port: 8080

#日志
logging:
  level:
    root: info
    com.scut.indoorLocation.dao: trace

#levelDB
levelDB:
  dir:
    path: "./levelDB"


#图片地址
image:
  dir:
    path: "C:/Users/Mingor/Desktop/室内定位服务项目/indoor_location/images"


