#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/location?characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    host: smtp.163.com
    username: location_2019@163.com
    password: location2019
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 5MB

# tomcat 参数
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 5MB

#日志
logging:
  level:
    root: info
    com.scut.indoorLocation.dao: trace

#levelDB
levelDB:
  dir:
    path: "./levelDB"

#mqtt服务器配置
mqtt:
  host: "39.99.131.85"
  port: 1883

#图片地址
image:
  dir:
    path: "C:/Users/Mingor/Desktop/室内定位服务项目/indoor_location/images"


