spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/location?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20

server:
  port: 8080

logging:
  level:
    root: INFO
    com.scut.indoorLocation.dao: INFO

levelDB:
  dir:
    path: "/root/Downloads/back_end/levelDB"